# Generated by Django 2.2.1 on 2019-09-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_auto_20190828_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='darkVideoBackground',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.CharField(default='to be defined', max_length=20),
        ),
    ]
